export THESIS_PATH="$(dirname "$0" )"
export THESIS_DATA_PATH=$THESIS_PATH/data
export GGCNN_SCENES_PATH=$THESIS_DATA_PATH/scenes
export SHAPENET_PATH=$THESIS_DATA_PATH/datasets/raw/shapenet40
export JACQUARD_PATH=$THESIS_DATA_PATH/datasets/raw/jacquard_samples
export PREPROCESSED_PATH=$THESIS_DATA_PATH/datasets/preprocessed
export SIM_LOG_PATH=$THESIS_DATA_PATH/results/sim_logs
export RESULTS_PATH=$THESIS_DATA_PATH/results
export MODELS_PATH=$THESIS_DATA_PATH/3d_models/shapenetsem40
export VHACD_PATH=''
